---
- name: Converge
  hosts: all
  become: yes
  become_user: root
  become_method: doas
  vars:
    # Matomo
    matomo_bypass_mysql: true
    matomo_bypass_nginx: true
    matomo_mysql_database: matomodata
    matomo_mysql_user: matomo
    matomo_mysql_password: matomo
    matomo_superuser_user: admin
    matomo_superuser_password: adminadmin42
    matomo_version: "3.9.0"
    matomo_name: localhost
    matomo_superuser_email: admin@example.org
    # MySQL
    mysql_databases:
      - name: "{{ matomo_mysql_database }}"
    mysql_users:
      - name: "{{ matomo_mysql_user }}"
        password: "{{ matomo_mysql_password }}"
        priv: "*.*:FILE/{{ matomo_mysql_database }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE\ TEMPORARY\ TABLES,LOCK\ TABLES"
    mysql_db_admin_password: adminpassword
    # httpd
    httpd_conf_domains:
      - name: matomo
        config: |
          listen on 127.0.0.1 port 80
          directory index index.php
          root "/matomo"
          location "*.php" {
            fastcgi socket "/run/php-fpm.sock"
          }
    # Misc
    dependencies:
      - php%7.4
      - php-gd%7.4
      - php-pdo_mysql%7.4
      - php-curl%7.4
      - gtar-1.34-static
  tasks:
    - name: "Include tleguern.mysql"
      include_role:
        name: "tleguern.mysql"
    - name: Install testing dependencies
      openbsd_pkg:
        name: "{{ dependencies }}"
        state: present
    - name: Configure pdo_mysql
      file:
        src: "/etc/php-7.4.sample/{{ item }}"
        dest: "/etc/php-7.4/{{ item }}"
        state: link
      loop: ['pdo_mysql.ini', 'gd.ini', 'curl.ini']
    - name: Start php-fpm
      service:
        name: php74_fpm
        state: started
        enabled: yes
    - name: "Include reallyenglish.httpd"
      include_role:
        name: "reallyenglish.httpd"
    - name: "Include ansible-matomo"
      include_role:
        name: "ansible-matomo"
